export { default as LandingPage } from "./pages/MainPages/LandingPage"
export { default as Login } from "./pages/Authentication/Login"
export { default as SignUp } from "./pages/Authentication/SignUp"
export { default as Welcome } from "./pages/MainPages/WelcomePage"
export { default as Dashboard } from "./pages/Dashboard/Dashboard"
export { default as Adventures } from "./pages/Adventures/Adventures"
export { default as MarketplacePage } from "./pages/Marketplace/MarketplacePage"
export { default as AuctionPage } from "./pages/MarketplaceList/AuctionPage"
export { default as ArcadePage } from "./pages/MarketplaceList/ArcadePage"
export { default as WatchFacePage } from './pages/MarketplaceList/WatchFacePage'
export { default as WatchRingtonesPage } from './pages/MarketplaceList/WatchRingtonesPage'
